spring:
  application:
    name: zuul-filter

server:
  port: 8180

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#  \u6D4F\u89C8\u5668\u8BBF\u95EE:http://127.0.0.1:8180/ ,Zuul \u4F1A\u53BB Eureka \u670D\u52A1\u6CE8\u518C\u4E2D\u5FC3\uFF0C\u627E\u5230provider-server\u670D\u52A1\u4EE5\u5747\u8861\u8D1F\u8F7D\u7684\u65B9\u5F0F\u8BBF\u95EE
zuul:
  routes:
    api:
      path: /**
      serviceId: provider-server